import Layout from "@/components/Layout";
import Head from "next/head";

export default function Home() {
  return (
    <Layout>
      <Head>
        <title>Project 3</title>
        <meta name="description" content="Generated by Project 3" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="max-w-lg mx-auto my-12">
          <ul className="list-group">
            <li className="list-group-item">
              <a href="/t1/1a/">Task 1a</a>
            </li>
            <li className="list-group-item">
              <a href="/t1/1b/">Task 1b</a>
            </li>
            <li className="list-group-item">
              <a href="/t2">Task 2</a>
            </li>
            <li className="list-group-item">
              <a href="/t3">Task 3</a>
            </li>
            <li className="list-group-item">
              <a href="/t4">Task 4</a>
            </li>
            <li className="list-group-item">
              <a href="/t5">Task 5</a>
            </li>
            <li className="list-group-item">
              <a href="/t6">Task 6</a>
            </li>
            <li className="list-group-item">
              <a href="/t7">Task 7</a>
            </li>
          </ul>
        </div>
      </main>
    </Layout>
  );
}
